import { jsPDF } from "jspdf";
import "jspdf-autotable";
import { formatCurrency, formatDate } from "./helpers";

export const generateTransactionsPdf = (transactions, unitLabel, userEmail) => {
  const doc = new jsPDF();
  const title = "Flowly Transactions Report";
  const date = new Date().toLocaleDateString();

  doc.setFontSize(16);
  doc.text(title, doc.internal.pageSize.getWidth() / 2, 20, {
    align: "center",
  });

  doc.setFontSize(10);
  doc.text(`Generated by: ${userEmail}`, 10, 30);
  doc.text(`Date: ${date}`, doc.internal.pageSize.getWidth() - 10, 30, {
    align: "right",
  });

  const tableColumn = [
    "Date",
    "Type",
    "Customer/Vendor",
    "Account",
    "Money In",
    "Money Out",
    `Units (${unitLabel})`,
    "Notes",
  ];
  const tableRows = [];

  transactions.forEach((t) => {
    const transactionData = [
      formatDate(t.date),
      t.type,
      t.customerVendor,
      t.accountName, // Assuming accountName is available
      t.moneyIn ? formatCurrency(t.moneyIn) : "-",
      t.moneyOut ? formatCurrency(t.moneyOut) : "-",
      t.units || "-",
      t.notes || "-",
    ];
    tableRows.push(transactionData);
  });

  doc.autoTable({
    head: [tableColumn],
    body: tableRows,
    startY: 40,
    styles: { fontSize: 8, cellPadding: 2, overflow: "linebreak" },
    headStyles: { fillColor: "#4F46E5", textColor: "#FFFFFF" }, // Primary brand color
    margin: { top: 10, right: 10, bottom: 10, left: 10 },
  });

  doc.save("flowly_transactions_report.pdf");
};
